spring.config.import=optional:file:.env[.properties]
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.application.name=lg-able-band-backend
server.port=8080
db.host=${DB_HOST:}
db.port=${DB_PORT:}
db.name=${DB_NAME:}
db.user=${DB_USER:}
db.password=${DB_PASSWORD:}
